### ISSUE TITLE
Reduce swiping sensitivity?

### ISSUE THREAD

**Issue by creativemind1** [swaplet/react-native-swipe-cards-deck#10]
It looks like there's a high sensitivity for swiping. When I'm scrolling vertically hold my first swiper image, it somehow tends to swipe a little left or right unexpectedly. This I've confirmed with `onDragStart` and `onDragRelease`.  Dragging starting (in my case left swipe) when we are vertically scrolling without intending to left swipe. 

Is there any way to reduce this sensitivity of leftSwipe or Right swipe while vertically scrolling your view content?

**Comment by eyalabs** [comment]
Check #8...
Controlling touch sensitivity is currently not supported. Maybe in later versions.

**Comment by eyalabs** [comment]
will be included in v3.0

**Comment by Saad9624** [comment]
> will be included in v3.0

any update on this?
