### ISSUE TITLE
on scrollview not swipe

### ISSUE THREAD

**Issue by Kuldeenagar** [swaplet/react-native-swipe-cards-deck#17]
When i swipe card view in between scrollview is not working and card stuck and not moving

**Comment by eyalabs** [comment]
I can't understand you. But please check out closed issues before opening new ones - #8

**Comment by Kuldeenagar** [comment]
when i add card info under scrollview then scrollview not working.
like:-
<View style={[styles.card, { backgroundColor: data.backgroundColor }]}>
      <ScrollView>
      <Image 
        style={{width:"100", height:100 }}
        source={data.imgurl}
      />
</ScrollView>
</View>
