### ISSUE TITLE
iOS stack rendering

### ISSUE THREAD

**Issue by JSDevelopment17** [swaplet/react-native-swipe-cards-deck#19]
Hi.

This may not be intentional (i.e. may not be an issue) but when I use the stackoffsetY on iOS the first offset card appears to have a bigger offset relative to subsequent cards. I've attached a screenshot below with code:
`stack={true}
stackDepth={3}
stackOffsetY={-25}`

<img width="229" alt="Screenshot 2021-08-27 at 16 52 04" src="https://user-images.githubusercontent.com/33499076/131154778-f33128ab-7c23-4c77-942e-649cd33369e8.png">

Hopefully just missing something very obvious!

Thanks,
Steve.

**Comment by LukasMod** [comment]
I handled this in my project (stack with visible cards at bottom, not top) by adding 1 to the index in the offsetY const of the renderStack() function: 
` let offsetY = this.props.stackOffsetY * cards.length - (i + 1) * this.props.stackOffsetY`

**Comment by JSDevelopment17** [comment]
Thanks for this. Worked a treat!
