### ISSUE TITLE
onClickHandler not working

### ISSUE THREAD

**Issue by NikLucoz** [swaplet/react-native-swipe-cards-deck#21]
Hi, when i try to use onCLickHandler on the swipe card i don't recive the default alert.
This is the code i used:

 ```
render() {
    return (
      <SwipeCards
        cards={this.state.cards}
        renderCard={(cardData) => <Card {...cardData} />}
        keyExtractor={(cardData) => String(cardData.text)}
        renderNoMoreCards={() => <NoMoreCards />}
        handleYup={this.handleYup}
        handleNope={this.handleNope}
        dragY={false}
        onClickHandler={alert("click")}
      />
    )
  }
```

**Comment by eyalabs** [comment]
You are not doing it right, you should give the handler a function ```onClickHandler={()=>alert("click")}```

BTW: I recommend you handling on-click within your component (when rendering a card, render it with on-click inside it so you'll have full control over what is clicking.
