### ISSUE TITLE
Change the card position / index from external Event.

### ISSUE THREAD

**Issue by Saad9624** [swaplet/react-native-swipe-cards-deck#24]
Is there any way to change the position/index of card from external button ?

**Comment by eyalabs** [comment]
Hello, 
Position and index are two different things. Please be more specific... 

The position of the cards is up to the parent component.

**Comment by Saad9624** [comment]
@eyalabs is there any way to change the height of images in Stack mode. just like the opacity.

**Comment by eyalabs** [comment]
You are the one that is responsible for rendering the content (including the image in the card), so yes, the image height is controlled by your component in your code
