### ISSUE TITLE
cards are not draggable in stack mode

### ISSUE THREAD

**Issue by eyalabs** [swaplet/react-native-swipe-cards-deck#3]
When using stack mode, cards don't react to touch events as supposed to (like in non-stack mode)

**Comment by RookTKO** [comment]
Cards are draggable on ios but not Android. Also cards seem to be off on android.
![image](https://user-images.githubusercontent.com/16005493/106695047-a3a20d80-658e-11eb-9340-499ea4460e56.png)

**Comment by eyalabs** [comment]
fixed in the ver 0.2.19
