### ISSUE TITLE
dragY prop doesn't work

### ISSUE THREAD

**Issue by eyalabs** [swaplet/react-native-swipe-cards-deck#4]

**Comment by RookTKO** [comment]
@eyalabs is this related to the previous issue? I think this is a android specific issue and not related to dragY. Again, with the recent changes you can stack now and swipe on ios but on android emulater when I try to swipe it won't let me. I'm personally at a bit of a lost atm. I'll have to come back to this in a few days. I don't know what specific native setting in the panHandler could be causing this.

**Comment by eyalyoli** [comment]
Don't think so, but I'll check it by the end of the week.

**Comment by eyalabs** [comment]
fixed in latest ver
