### ISSUE TITLE
Starting animation fires every redux store update

### ISSUE THREAD

**Issue by DiegoDevBittencourt** [swaplet/react-native-swipe-cards-deck#5]
I tried to remove the `useSelector(state =>...)` from the components and it stopped this behavior, but well... I need the redux into my components. Also the older version `react-native-swipe-cards` is working fine without this animation firing everytime.

A gif to ilustrate:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/21102506/106853094-e8fe3200-6697-11eb-9464-75122f534532.gif)

**Comment by eyalyoli** [comment]
If what you assigned to cards prop is an always changing list, the animation will keep firing. 
Redux is just a store for your data, something in your code is triggering a change to your cards list. 

Please check your code for anything that makes changes to your cards list - this is your problem.

**Comment by DiegoDevBittencourt** [comment]
Actually this time I'm using this array:
```
const cards = [
        { id: 1, text: 'Tomato', backgroundColor: 'orange' },
        { id: 2, text: 'Aubergine', backgroundColor: 'purple' },
        { id: 3, text: 'Courgette', backgroundColor: 'green' },
        { id: 4, text: 'Blueberry', backgroundColor: 'blue' },
        { id: 5, text: 'Umm...', backgroundColor: 'red' },
        { id: 6, text: 'orange', backgroundColor: 'cyan' },
    ]
```
A piece of my code: 
```
<SwipeCards
            keyExtractor={item => item.id.toString()}
            cards={cards}
            renderCard={(cardData) => <View style={{ height: 200, width: 200 }} {...cardData} />}
            ...
```
In this component, yes, I have some call to redux store but it's not actually beying used by swipe cards, again, this behavior doesn't exists on the older version `react-native-swipe-cards`. Do you have any idea how to fix that?

**Comment by eyalyoli** [comment]
1. Why do you spread the card data into the view attributes - it is not right
2. The code you attached doesn't help 
3. Just try to comment-out lines from your code (one at a time) that can trigger any change to the data or the UI elements.

**Comment by DiegoDevBittencourt** [comment]
1 - Changed to this:
```
const TestComponent = ({ backgroundColor }) => <View style={{ height: 200, width: 200, backgroundColor }} />

export default function Test() {
    
        const [randomVar, setRandomVar] = useState(true);

        const cards = [
            { id: 1, text: 'Tomato', backgroundColor: 'orange' },
            { id: 2, text: 'Aubergine', backgroundColor: 'purple' },
            { id: 3, text: 'Courgette', backgroundColor: 'green' },
        ]
        
        return <MainContainer>
        <Button title={randomVar.toString()} onPress={() => setRandomVar(!randomVar)} />
        <SwipeCards
            keyExtractor={item => item.id.toString()}
            cards={cards}
            renderCard={(cardData) => <TestComponent {...cardData} />}
            ...
}
```

2 - Updated the code.
3 - Removed all redux code, added a simple useState. Seems like the problem is when the component rerender.

![wwwwwwwwwww](https://user-images.githubusercontent.com/21102506/106961572-8e5ae980-671c-11eb-93ff-1a46c52c20ba.gif)

**Comment by eyalyoli** [comment]
I already said so, it is called an entrance animation and it starts on every new render to the whole swipe cards component. 

I use tens of states inside a complex screen which has the swipe cards in it and the only time that the animation gets triggered is when i switch the cards list. 

What you have here is the whole parent component of swipe cards re-renders all the time (and for nothing). This is the root issue here. 

Best recommendation i have for you is to start clean with a stable code and to read best practices about reducing unneeded rendering of components - try to use pure components. 

I'll post a clean code with a an inner state later as an example.

**Comment by DiegoDevBittencourt** [comment]
Can't you make this "entrance animation" fires only on the mount of the card, just like the `react-native-swipe-cards` version? I added a `useEffect` to the card component to track if it was beying recreated and no, it only rerenders, it's not recreating the component.

```
added this to the card component:

useEffect(()=> {
      console.log('test'); // only firing once
}, []);
```

**Comment by eyalyoli** [comment]
I said i have the component in a screen with lots of changing state and i didn't reproduce the problem. I'll try to make a minimal working real example with changing states. 
If i reproduce it i can fix it. If not then it is specific to your code. I'll update you.

**Comment by eyalabs** [comment]
Hi again, I've updated the example to include a loading state + remote fetching of data.

With the same example I've tested what you said by adding additional counter state when a button clicked and it didn't affect the cards when the counter changed.
Note that the example is in functional style (not component) as it is the recommended to implement with react.
I hope this helps.
