### ISSUE TITLE
How can I fire the animation from a outside button?

### ISSUE THREAD

**Issue by DiegoDevBittencourt** [swaplet/react-native-swipe-cards-deck#6]
I'm building a tinder like app and would be nice if when the user press the "I don't like it" button for example, the card goes to the left by itself.

**Comment by eyalyoli** [comment]
Just make a ref to the swipe card component and call `_forceLeftSwipe()` and `_forceRightSwipe()` accordingly.

**Comment by DiegoDevBittencourt** [comment]
Nice, Worked like a charm! I added this ref to redux store and it's working fine too.

The problem now is that if I update the `cards` prop right after the click, it won't let the animation finish and already start the "entrance animation" of the next card. Would be nice if we have something like: `swipeCardRef._forceLeftSwipe().then(()=> ...);` so on `then()` we would put the code to update the cards array. Or we already have something like that?

**Comment by eyalyoli** [comment]
Sorry, but you are using the lib in the wrong way! 
You shouldn't update the cards list after a swipe. You should let the lib do its job and replace the shown card from the list when the user swipe right/left.

**Comment by DiegoDevBittencourt** [comment]
@eyalyoli I'm building an app in tinder style, so, I can't download all possible profiles at once. At the moment I'm downloading 2 profiles per time, so when the user likes or dislike someone, the app will download another profile and store in n array in redux store, that's directly connected to `cards` prop.
What do you suggest in this use case?

**Comment by eyalyoli** [comment]
You have a design issue that is not related to the lib. I suggest you load more profiles in advance as 2 is too low. 

When you wish to load more profiles, networking on mobile phone can take time (not as fast as your testing env), so you'll have to make a "loading" state for the card deck. After this loading is done it is okay to fire the entrance animation and it is right. This behavior will not change. 

I can make an option to cancel the entrance animation, but this is not the right solution for you design issue and it will take time developing (or you can suggest a PR).
